### 1. Create a DataFrame
- Create a DataFrame with columns `Name`, `Age`, and `Marks`.
- Include 4 student records with at least one missing value.
- Hint: Use a dictionary and `pd.DataFrame()`.

In [48]:
import pandas as pd

data = {
    'Name': ['Anu', 'Rahul', 'Manu', 'Neha'],
    'Age': [20, None, 24, 22],
    'Marks': [85, 78, 92, 88]
}

df = pd.DataFrame(data)
print(df)

    Name   Age  Marks
0    Anu  20.0     85
1  Rahul   NaN     78
2   Manu  24.0     92
3   Neha  22.0     88

### 2. Add a New Column
- Add a new column `Grade` with letter grades (A, B, C, etc.).

In [49]:
df['Grade'] = ['A+', 'A', 'B+', 'B']
print(df)

    Name   Age  Marks Grade
0    Anu  20.0     85    A+
1  Rahul   NaN     78     A
2   Manu  24.0     92    B+
3   Neha  22.0     88     B

### 3. Access Specific Columns
- Display only the `Name` and `Marks` columns.

In [50]:
print(df[['Name', 'Marks']])

    Name  Marks
0    Anu     85
1  Rahul     78
2   Manu     92
3   Neha     88

### 4. Count Missing Values
- Count the number of missing values in each column.
- Hint: `df.isnull().sum()`.

In [51]:
print(df.isnull().sum())

Name     0
Age      1
Marks    0
Grade    0
dtype: int64

### 5. Handle Missing Values
- Replace all missing values in `Age` with the mean age.
- Hint: `df['Age'].fillna(df['Age'].mean(), inplace=True)`.

In [52]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df)

    Name   Age  Marks Grade
0    Anu  20.0     85    A+
1  Rahul  22.0     78     A
2   Manu  24.0     92    B+
3   Neha  22.0     88     B

### 6. Modify a Specific Cell
- Change the `Name` in the 3rd row (index 2) to `Sonu`.
- Hint: `df.loc[2, 'Name'] = 'Sonu'`.

In [53]:
df.loc[2, 'Name'] = 'Sonu'
print(df)

    Name   Age  Marks Grade
0    Anu  20.0     85    A+
1  Rahul  22.0     78     A
2   Sonu  24.0     92    B+
3   Neha  22.0     88     B

### 7. Add New Rows to the DataFrame
- Add two new rows:
  - `{'Name': 'Kumar', 'Age': 20, 'Marks': 90}`
  - `{'Name': 'Rahul', 'Age': 26, 'Marks': 85}`
- Hint: Use `pd.concat()`.

In [54]:
new_names = pd.DataFrame([
    {'Name': 'Kumar', 'Age': 20, 'Marks': 90},
    {'Name': 'Rahul', 'Age': 26, 'Marks': 85}
])

df = pd.concat([df, new_names], ignore_index=True)
print(df)

    Name   Age  Marks Grade
0    Anu  20.0     85    A+
1  Rahul  22.0     78     A
2   Sonu  24.0     92    B+
3   Neha  22.0     88     B
4  Kumar  20.0     90   NaN
5  Rahul  26.0     85   NaN

### 8. Access Data Using loc
- Access and print `Name` and `Marks` for the student at index 0.
- Hint: `df.loc[0, ['Name', 'Marks']]`.

In [55]:
print(df.loc[0, ['Name', 'Marks']])

Name     Anu
Marks     85
Name: 0, dtype: object

### 9. Slicing Rows and Columns Using loc
- Display `Name` and `Marks` for rows 0 to 3.
- Hint: `df.loc[0:3, ['Name', 'Marks']]`.

In [56]:
df.loc[0:3, ['Name', 'Marks']]

    Name  Marks
0    Anu     85
1  Rahul     78
2   Sonu     92
3   Neha     88

### 10. Access Rows and Columns Using iloc
- Display the first and third rows, and the first two columns.
- Hint: `df.iloc[0:3:2, 0:2]`.

In [57]:
df.iloc[0:3:2, 0:2]

   Name   Age
0   Anu  20.0
2  Sonu  24.0

### 11. Aggregate Functions
Calculate and display:
- Mean Age
- Minimum Age
- Maximum Age
- Count of Age values

In [58]:
print("Mean Age:", df['Age'].mean())
print("Minimum Age:", df['Age'].min())
print("Maximum Age:", df['Age'].max())
print("Count of Age values:", df['Age'].count())

Mean Age: 22.333333333333332
Minimum Age: 20.0
Maximum Age: 26.0
Count of Age values: 6

### 12. Grouping and Aggregation
- Group the DataFrame by `Name` and compute the mean `Age` for each name.
- Hint: `df.groupby('Name')['Age'].mean()`.

In [59]:
df.groupby('Name')['Age'].mean()

Name
Anu      20.0
Kumar    20.0
Neha     22.0
Rahul    24.0
Sonu     24.0
Name: Age, dtype: float64

### Bonus Challenge
- Sort the DataFrame by `Marks` in descending order.
- Display the top 3 students.
- Hint: `df.sort_values(by='Marks', ascending=False).head(3)`.

In [60]:
df.sort_values(by='Marks', ascending=False).head(3)

    Name   Age  Marks Grade
2   Sonu  24.0     92    B+
4  Kumar  20.0     90   NaN
3   Neha  22.0     88     B